const COLOR_SUCCESS = '#4caf50';
const COLOR_WARNING_LEVEL_1 = '#ffb52d';
const COLOR_WARNING_LEVEL_2 = '#FF9900';
const COLOR_WARNING_LEVEL_5 = '#70432a';
const COLOR_INFO_LEVEL_1 = '#18222E';
const COLOR_INFO_LEVEL_2 = '#232f3e';
const COLOR_INFO_LEVEL_3 = '#2D3B4D';
const COLOR_INFO_LEVEL_4 = '#37485D';
const COLOR_INFO_LEVEL_5 = '#435272';
const COLOR_INFO_LEVEL_6 = '#36B2DE';
const COLOR_ALERT = '#ff5722';
const COLOR_WHITE = '#ffffff';
const COLOR_GRAY_LEVEL_3 = '#79899C';
const COLOR_GRAY_LEVEL_5 = '#1c1c1c';

export {
  COLOR_WHITE,
  COLOR_ALERT,
  COLOR_INFO_LEVEL_1,
  COLOR_INFO_LEVEL_2,
  COLOR_INFO_LEVEL_3,
  COLOR_INFO_LEVEL_4,
  COLOR_WARNING_LEVEL_1,
  COLOR_WARNING_LEVEL_2,
  COLOR_SUCCESS,
  COLOR_GRAY_LEVEL_3,
  COLOR_GRAY_LEVEL_5,
  COLOR_INFO_LEVEL_5,
  COLOR_INFO_LEVEL_6,
  COLOR_WARNING_LEVEL_5,
};
