
const STATUS_ONLINE = 'ONLINE';
const STATUS_OFFLINE = 'OFFLINE';
const LIMIT_TEMPERATURE = 40;
const TYPE_TEMPERATURE = 'TEMPERATURE';
const TYPE_FALL = 'FALL';

export {
  STATUS_ONLINE,
  STATUS_OFFLINE,
  LIMIT_TEMPERATURE,
  TYPE_TEMPERATURE,
  TYPE_FALL,
};